// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP8bM5IPZ2x94AwvjWeY2ODEC_3rMDFVs',
    appId: '1:207859538194:android:1b9bb3483b18663858fbcb',
    messagingSenderId: '207859538194',
    projectId: 'homeflix-438f9',
    storageBucket: 'homeflix-438f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-w0QyJ4y6bR8suCqkyzqVWlCDOvp-oE',
    appId: '1:207859538194:ios:bddfc6da9b47cf8e58fbcb',
    messagingSenderId: '207859538194',
    projectId: 'homeflix-438f9',
    storageBucket: 'homeflix-438f9.firebasestorage.app',
    iosBundleId: 'com.youvataque.homeflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-w0QyJ4y6bR8suCqkyzqVWlCDOvp-oE',
    appId: '1:207859538194:ios:bddfc6da9b47cf8e58fbcb',
    messagingSenderId: '207859538194',
    projectId: 'homeflix-438f9',
    storageBucket: 'homeflix-438f9.firebasestorage.app',
    iosBundleId: 'com.youvataque.homeflix.mac',
  );

}